on:
    push:
        branches:
            - master
    pull_request:

name: Coding Standards

jobs:
    open-pr-for-cs-violations:
        name: PHP-CS-Fixer
        runs-on: ubuntu-20.04
        if: github.actor != 'dependabot[bot]'
        steps:
            -   name: Checkout code
                uses: actions/checkout@v3
                with:
                    ref: ${{ github.head_ref }}

            -   name: Run PHP-CS-Fixer
                uses: docker://oskarstark/php-cs-fixer-ga:3.11.0

            -   name: Commit and push back changes
                uses: stefanzweifel/git-auto-commit-action@v4
                with:
                    commit_message: "Fix CS with PHP-CS-Fixer"
